### ISSUE TITLE
Weird message

### ISSUE THREAD

**Issue by cdrik6** [hamoid/video_export_processing#10]
Quite boring to create a video with processing, your lib is very welcome!

So I used your lib, but when i ran my sketch i got that message:
Mar 22, 2016 12:37:45 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

Is it important? Do not really understand the meaning...

Then i get a video, but quite faster that it should be.
My goal is to draw on a movie.
In my sketch i set frameRate(25) and videoExport.setFrameRate(25), but the resulting video is not at the right speed as if the video missed some frames.

Here is my sketch FYI:

import com.hamoid.*;
import processing.video.*;

Movie mov;
VideoExport videoExport;

void setup()
{
  size(1280, 720);
  background(0);  
  frameRate(25); 
   
  videoExport = new VideoExport(this, "testout.mp4");
  videoExport.setFrameRate(25);
  videoExport.setQuality(70);
  
  mov = new Movie(this, "test.mp4");  
  mov.play();
}

void movieEvent(Movie m)
{
  m.read();
}

void draw()
{
  background(0);
  image(mov, 0, 0, width, height);  
  
  fill(255);
  text("Frame Number : " + FrameNber() + " / " + TotFrames() + " / " + mov.frameRate , 10, 30);
  text("Frame Counter : " + frameCount, 10, 40);
  
  stroke(0);
  strokeWeight(20);
  line(0, height/2, frameCount, height/2);
    
  videoExport.saveFrame();
}

int TotFrames()
{
  return int(mov.duration() * mov.frameRate);
}

int FrameNber()
{    
  return ceil(mov.time() * mov.frameRate) - 1;
}

**Comment by hamoid** [comment]
Hi! Thank for posting this. I updated the library and I hope the error you got is now gone. The reason was that the preferences were being saved in a location that needed root access. Now the preferences are saved in a different location, which should require no privileges.

About the speed issue, I can imagine that what happens is this:
Processing plays the video. The sound from the video is what sets the current time. The sound can not be stretched or be glitchy. If Processing is not fast enough to play on time each frame from the video, then it just skips frames. It shows whatever frames it can, in sync with the audio. At the end, you have some missing frames from the resulting video, because it was not fast enough. 

I can think of two solutions:

A) Extract all frames from the video as single images. You can use ffmpeg for that. Then you modify your program to load single frames from disk, instead of loading the video. That way each single frame would be processed for sure.

or

B) Play your video at a lower frame rate. For instance, set the video to be played at 10 frames per second, your Processing sketch also at 10 fps, but the output video still at 25 fps. Then (I hope) the processing happens at a lower speed, not missing frames, and the resulting video is still 25 fps.

In any case I don't think this is a issue of the VideoExport library, but just how video playing works, and it has to be worked around.

**Comment by cdrik6** [comment]
Many thanks Abe for your quick and full detailed answer, will try your solutions and let you know.

More, I often use your tutorials on funprogramming, and because of you i discovered SuperCollider, which sounds great (but not easy for me).

When i searched a lib for video, and i saw it was yours, so i said let’s go, it’s Abe, you will learn something!

Great Job!
Cédric
