### ISSUE TITLE
build video not working in Win 10

### ISSUE THREAD

**Issue by rongloveyan** [hamoid/video_export_processing#22]
```
if (process != null) {
    process.destroy();
    try {
        process.waitFor();
    } catch (InterruptedException e) {
        PApplet.println("Waiting for ffmpeg timed out!");
        e.printStackTrace();
    }
}
```

i think this code should be fixed as follow

```
if (process != null) {
    try {
        process.waitFor();
        process.destroy();
    } catch (InterruptedException e) {
        PApplet.println("Waiting for ffmpeg timed out!");
        e.printStackTrace();
    }
}
```

**Comment by hamoid** [comment]
Hi! Thanks for the suggestion. I've been reading about destroying processes and it's not clear to me. destroy() may or may not forcibly destroy the process (according to the java documentation). This could be why in Linux it works fine, but in Windows it doesn't. waitFor() will block the execution until the program is done, but I suspect this would never happen in this case, because it's waiting for input (images). So I think I will first try do this and see if it fixes the issue:
```
			try {
				Thread.sleep(1000);
				process.destroy();
				process.waitFor();
			} catch (InterruptedException e) {
				PApplet.println("Waiting for ffmpeg timed out!");
				e.printStackTrace();
			}
```
I don't know if giving it 1 second will change anything though. If it's forcibly closed, the video metadata will be missing from the end of the file. So how can I tell the ffmpeg process that we are done? I'll keep reading.

**Comment by hamoid** [comment]
This is exactly what's going on: https://stackoverflow.com/questions/27942679/how-to-terminate-a-process-normally-created-using-processbuilder

**Comment by hamoid** [comment]
@rongloveyan could you try downloading the latest version see if it works? I added the 1 second delay before destroying...

**Comment by rongloveyan** [comment]
yes, it  worked .thanks

**Comment by Scarfmonster** [comment]
I looked into this, and it seems that out of the box Windows doesn't support sending SIGINT to a process beyond using Ctrl-C when it's open in the command prompt. I guess that's why .destroy() on Windows sends SIGKILL instead of SIGINT like on Linux.

The only way to send a SIGINT to ffmpeg on Windows I found is using [SendSignal.exe](http://www.latenighthacking.com/projects/2003/sendSignal/). I tried to do a really dirty hack and it kind of works but I have no idea how to get a PID of a specific process in Java outside of calling Windows' tasklist and then parsing it with regex. 

Bear in mind this was basically glued together as I worked out how to even do something like this, so it works but I have no idea if it will work on other Windows versions. I also have barely any Java experience so I'm sure this can be cleaned up somehow. It also assumes SendSignal.exe is inside the sketch's data directory.

                // This delay is to avoid creating corrupted video files.
                // I'm not sure it is useful.
                Thread.sleep(500);

                //Do not call .destroy(), try sending SIGINT instead
                //process.destroy();
                
                //Get the PID of the ffmpeg.exe process.
                ArrayList<String> c = new ArrayList<String>();
                c.add("tasklist");
                c.add("/FI");
                c.add("\"IMAGENAME eq ffmpeg.exe\"");
        
                ProcessBuilder ps = new ProcessBuilder(c);
                Process pr = ps.start();
                pr.waitFor();
                BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream()));
                if (pr.exitValue()==0) {
                  //Skip first three lines
                  in.readLine();
                  in.readLine();
                  in.readLine();
                } else {
                  println("Error while getting PID", pr.exitValue());
                  BufferedReader err = new BufferedReader(new InputStreamReader(pr.getErrorStream()));
                  
                  String errm = "";
                  while ((errm = err.readLine()) != null) {
                    println(errm);
                  }
                }
                
                //Get the PID from the fourth line
                Pattern pattern = Pattern.compile("([0-9]+)");
                Matcher matcher = pattern.matcher(in.readLine());
                matcher.find();
                
                Runtime.getRuntime().exec(parent.sketchPath("data\\SendSignal.exe") + " " + matcher.group(1));
        
                process.waitFor();

**Comment by hamoid** [comment]
Thank you @Scarfmonster ! Great find :) I'll think about how to implement this without making it too complicated for the user. Happy end of year!

**Comment by hamoid** [comment]
Looking for GenerateConsoleCtrlEvent I found this java library: https://github.com/java-native-access/jna/tree/master/dist There's a jar for Win64. In this file https://github.com/java-native-access/jna/blob/master/contrib/platform/src/com/sun/jna/platform/win32/Wincon.java they provide a GenerateConsoleCtrlEvent() method that might work, to send a ctrl-c signal to a process.

Do you think you would be able to try this @Scarfmonster ? If it works it would be great, because I could add this jar file to the project without needing to ask people to download SendSignal.exe.

I also tried to simplify your code. It's untested, but it might look like this:

```java
                //Do not call .destroy(), try sending SIGINT instead
                //process.destroy();

                //Get the PID of the ffmpeg.exe process.
                ProcessBuilder ps = new ProcessBuilder("tasklist");
                Process pr = ps.start();
                pr.waitFor();

                //Get the PID in the list
                BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream()));
                Pattern pattern = Pattern.compile("ffmpeg\\.exe.*?([0-9]+)");
                while(true) {
                    Matcher m = pattern.matcher(in.readLine());
                    if (m.find()) {
                        Runtime.getRuntime()
                                .exec(parent
                                        .sketchPath("data\\SendSignal.exe") +
                                        " " + m.group(1));
                        break;
                    }
                }

                process.waitFor();
```

Now that I see it, it needs a way to react to in.readLine() being empty. Well it's work in progress :)

**Comment by Scarfmonster** [comment]
Your code works with a slight modification. I am not sure myself if we actually need the pr.waitFor() at all. Buffered reader will wait for the process' output itself, and the wait where you had it blocked forever because the process was waiting for anything to read it's output.
```java
                //Do not call .destroy(), try sending SIGINT instead
                //process.destroy();

                //Get the PID of the ffmpeg.exe process.
                ProcessBuilder ps = new ProcessBuilder("tasklist");
                Process pr = ps.start();

                //Get the PID in the list
                BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream()));
                Pattern pattern = Pattern.compile("ffmpeg\\.exe.*?([0-9]+)");
                String line;
                while((line = in.readLine()) != null) {
                    Matcher m = pattern.matcher(line);
                    if (m.find()) {
                        Runtime.getRuntime()
                                .exec(parent
                                        .sketchPath("data\\SendSignal.exe") +
                                        " " + m.group(1));
                        break;
                    }
                }
                pr.waitFor();
                process.waitFor();
```
As for the library you mentioned, this seems to work:
```java
        import com.sun.jna.platform.win32.Wincon;
        import com.sun.jna.platform.win32.Kernel32;
        (...)
                //Get the PID of the ffmpeg.exe process.
                ProcessBuilder ps = new ProcessBuilder("tasklist");
                Process pr = ps.start();

                //Get the PID in the list
                BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream()));
                Pattern pattern = Pattern.compile("ffmpeg\\.exe.*?([0-9]+)");
                String line;
                while((line = in.readLine()) != null) {
                    Matcher m = pattern.matcher(line);
                    if (m.find()) {
                        Wincon wincon = Kernel32.INSTANCE;
                        wincon.GenerateConsoleCtrlEvent(Wincon.CTRL_C_EVENT, Integer.parseInt(m.group(1)));
                        
                        break;
                    }
                }

                process.waitFor();
```

I also found out that processing is using JNA too, but I don't know if you can import it inside a library/sketch. It also seems it only needs jna-platform.jar. I don't know what the platform-specific jars are for.

**Comment by hamoid** [comment]
Awesome @Scarfmonster ! Thanks for your help! :) I'll give it a try and see how to make it work cross platform.

**Comment by hamoid** [comment]
I applied the jna method to this release: https://www.funprogramming.org/VideoExport-for-Processing/download/VideoExport-17.zip

Could you give it a try and see if the examples run fine? Please press 'q' to end the sketch to make sure the video is closed properly.

**Comment by letapjar** [comment]
JHust looking over the code - seems like the attachSound method should probably do the same thing as the endMopvie method as far as saving ffmep-audio.txt and then deleting it later if saveDebugInfo is set to false. Otherwise the attachSound may not exit properly on Win 10

**Comment by hamoid** [comment]
You are right! I had this suspicion somewhere in my mind, but somehow I avoided looking at that part of the code :)
I just overwrote https://www.funprogramming.org/VideoExport-for-Processing/download/VideoExport-17.zip with your suggestion.

**Comment by hamoid** [comment]
According to feedback in the Processing forum, this issue is now solved and all examples work fine in Windows 10.
