### ISSUE TITLE
Could not find a library in the downloaded file

### ISSUE THREAD

**Issue by davideriboli** [hamoid/video_export_processing#35]
Hi,

I have your same problem as [written here](https://forum.processing.org/two/discussion/comment/95193/#Comment_95193): downloading the VideoExport library from inside Processing is giving "Could not find a library in the downloaded file.".

So, I've manually installed the library, but no luck! Library seems not working. Even if [correctly installed](https://photos.google.com/share/AF1QipPL4df654R9_6_xnBGEf-Wzum7P8ajh6PtxDyyL3IVuejf45JfUMshj9EtHh79ONQ?key=YllrclpsZFgtYTZ0OU9xYWUxa251NXdpUjBGYm9B), the instruction

`import com.hamoid.*;`

return this in console:

```
No library found for com.hamoid
Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.
```

VideoExport was downloaded from FunProgramming and my Processing version is 3.3 running under Linux 64 bit.

Everything seems to correctly work if using Processing 3.2.4.

**Comment by hamoid** [comment]
Hi! Very interesting. I need to investigate. I just installed the library manually with 5 students and it worked, and I assume they were on 3.3.

Can you verify that you installed the library in the right folder by looking at the Processing Preferences? It will show where is your sketch folder. I'm pretty sure you got it right, but the students changed the sketch folder by accident and then the library was not found.

Also, did you restart Processing?

I will ask why the library is not found. I wonder if it is because I switched the server from http to https...

**Comment by davideriboli** [comment]
Yes, lib is in the right folder and near other working libs.

My line about Processing 3.2.4 needs an update: everything is working only if you manually install it.

**Comment by hamoid** [comment]
I pushed version 0.1.8, in which I entered the server url as https. I don't know how often they scan library updates. This might make a difference in installing inside the IDE, but not with not finding the manually installed library.

I will try from a different Ubuntu machine. Thanks for reporting!

**Comment by hamoid** [comment]
I asked @prisonerjohn to update the URL and I hope it solves this issue soon.

**Comment by hamoid** [comment]
Seems to be fixed! I just tried and installed the library from the IDE. If still not working after restarting Processing please reopen this issue.
