### ISSUE TITLE
video framerate depends on sketch framerate

### ISSUE THREAD

**Issue by kahagino** [hamoid/video_export_processing#63]
I set `frameRate(60.0);` and
`videoExport.setFrameRate(30.0);`

if the sketch runs for 10s, I have an output of 20s. So the video is in slow-motion.
How can I have an independant output regardless of the sketch framerate ?

**Comment by hamoid** [comment]
Hi, the first thing that comes to mind with those numbers would be to save only every other frame. For example:
`if(frameCount % 2 == 0) videoExport.saveFrame();`

Or if the frame rate might not be stable, you could check `millis()` and decide if it's time to save a new frame or not. That would work assuming that the actual frame rate is higher than the requested video frame rate.

Would one of those approaches work for you?

**Comment by kahagino** [comment]
Yes the first solution works (now I understand why it's slow mo 🤗) but as you said, the framerate isn't constant and so a delay appears after some time.

In fact I'm trying to synchronize audio so it turned out like this:
`if (videoExport.getCurrentTime() < audio.position()) videoExport.saveFrame();`
So the video follows the audio which is in sync but the end result "jumps" too much (it's like some frames are skipped for too long)

I tried the following with millis() (sketch frameRate = 60 / video framerate = 30):

```
current_millis = millis();
  if (current_millis - previous_millis > 30) {
    videoExport.saveFrame();
    frame_counter += 1;
    previous_millis = current_millis; 
  }
```

A delay of about +10% appears (so the video is accelerated at the end)
maybe it needs some deeper calculations with millis() ?

thanks for your time!

**Comment by hamoid** [comment]
More questions: does in need to look good both live and in the recording?

Producing a video clip should not be hard: you can divide the sound length in seconds by 30 and that's how many frames you need. But having good real time visuals plus good video output needs some effort.

Have you seen this example? https://github.com/hamoid/video_export_processing/blob/master/examples/withAudioViz/withAudioViz.pde

One thing you could do is do it in two passes, if that is ok for you. One, your play the live graphics at 60 fps. While that happens, you record the data (possibly sound analysis, midi input, key presses, interactions...) required to produce the right video clip. Then on a second pass you can create `songDurationInSeconds * 30` frames using the recorded data. I've done this sometimes. The data should contain a timestamp (milliseconds since the movie start) plus whatever other data you need, for example key presses or knob turns on a midi controller. This data can have a higher resolution than needed, for example 60 entries per second. Then you produce the video clip frame by frame. You calculate the current frame's time in milliseconds, and then you advance in your stored data up to that point in time.

What do you think? Is that doable?

**Comment by kahagino** [comment]
This is the solution I was searching for! It's a good idea to make it in two passes 😉

Thanks a lot!
